myDickSize = input("What's your dick size?: ")
MyMasturbationScheule = input("When do you masturbate?: ")
print("Woah! Woah! That's a lot!")
ThreeSomeOverdose = input("Do you overdose on threesome?: ")
print("Woah Woah! you should seek medical help immediatly!")
print()
print("So, you dick size is")
print(myDickSize)
print("and you basically jack off around")
print(MyMasturbationScheule)
print("and your threesome overdose is")
print(ThreeSomeOverdose)
